@startuml

interface Function {
    + Double evaluate()
}

/'basic elements'/
class Variable implements Function {
    - Function function1
    - Function function2

    + Double evaluate()
}

class Number implements Function {
    - Function function1
    - Function function2

    + Double evaluate()
}

/'compound'/
class Sum implements Function {
    - Function function1
    - Function function2

    + Double evaluate()
    + String toString()
}

class Sub implements Function {
    - Function function1
    - Function function2

    + Double evaluate()
    + String toString()
}

class Mul implements Function {
    - Function function1
    - Function function2

    + Double evaluate()
    + String toString()
}

class Div implements Function {
    - Function function1
    - Function function2

    + Double evaluate()
    + String toString()
}

class Pow implements Function {
    - Function function1
    - Function function2

    + Double evaluate()
    + String toString()
}

class Sqrt implements Function {
    - Function element

    + Double evaluate()
    + String toString()
}

class Mod implements Function {
    - Function element

    + Double evaluate()
    + String toString()
}

@enduml